### ISSUE TITLE
Begin tests

### ISSUE THREAD

**Issue by TaylorBarrick** [lex-obrien/goSmartSheet#3]
Need to begin tests for regression

**Comment by TaylorBarrick** [comment]
I think this is covered by #2

**Comment by lex-obrien** [comment]
Closing!

**Comment by TaylorBarrick** [comment]
Hmmm

On May 20, 2017 11:34 PM, "lex-obrien" <notifications@github.com> wrote:

Closed #3 <https://github.com/lex-obrien/goSmartSheet/issues/3>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/lex-obrien/goSmartSheet/issues/3#event-1090728500>, or mute
the thread
